[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["someone"]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = "^3.7"
cowsay = "~=5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
